# Generated by Django 3.2.14 on 2022-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_App', '0002_auto_20220802_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
