# Generated by Django 3.2.14 on 2022-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_App', '0003_userdetails_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='images',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
