# Generated by Django 3.2.15 on 2022-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_App', '0004_auto_20220804_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='images',
            field=models.ImageField(default=None, max_length=200, upload_to=''),
        ),
    ]
